### ISSUE TITLE
Package name with hyphens should be converted to underscores

### ISSUE THREAD

**Issue by florimondmanca** [cs01/create-python-package#10]
I've just tried creating a Python package named `tartiflette-asgi` (:wink:) and the resulting Python package is called `tartiflette-asgi`. It should be `tartiflette_asgi` because hyphens aren't allowed in Python identifiers.

To be clear, if `name` contains hyphens:

- Keep the hyphenized name to create the project folder, project name, etc
- Convert hyphens to underscores when creating the package itself. Use a `.isidentifier()` check to be 100% sure.

FYI, I had to implement a similar thing in Bocadillo CLI; PR is here: https://github.com/bocadilloproject/bocadillo-cli/pull/3

**Comment by cs01** [comment]
Yeah this is a problem. Thanks for reporting, and thanks for the PR link.

> Python package named tartiflette-asgi

Awesome! You don't waste any time!

**Comment by cs01** [comment]
Using cookiecutter instead
