### ISSUE TITLE
Select test framework

### ISSUE THREAD

**Issue by florimondmanca** [cs01/create-python-package#5]
Currently, `create-python-package` sets up a sample test suite based off `unittest`. One other popular option (which I personally use) is `pytest`.

It would be cool if one could select their test framework, e.g. `unittest` and `pytest`, or choose to not have tests configured at all.

For `pytest`, a `pytest.ini` file should be generated to configure the test paths:

```ini
[pytest]
testpaths = tests/
```

**Comment by cs01** [comment]
Great suggestion, I was thinking about this too and would love for CPP to support it. 

I will have to try pytest, I've heard so many good things about it 😄.

**Comment by cs01** [comment]
It would probably be nice to add a tox option as well.

**Comment by florimondmanca** [comment]
Yes, I think a lot of people are using tox too — never tried it though! Have you? Any pointers as to what should be set up / generated (similar to pytest.ini)?

**Comment by cs01** [comment]
I've never used it either 😆 .

This is probably a good template to work from: https://github.com/pypa/sampleproject

**Comment by florimondmanca** [comment]
Taking a look at it. In retrospect, the `pytest.ini` file is not required. :-)
